-- EDIMAGE WORLD: Supabase bootstrap (free-tier friendly)
-- Run this once in Supabase SQL Editor.

create table if not exists public.knowledge_entries (
  id bigint generated by default as identity primary key,
  title text not null,
  author text default '',
  tags text default '',
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.world_stats (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.world_stats (key, value_json, updated_at)
values (
  'access_state',
  jsonb_build_object(
    'inviteCompletions', 0,
    'completedSessions', jsonb_build_array(),
    'issuedInviteSessions', jsonb_build_array(),
    'totalStoryCompletions', 0,
    'completedStorySessions', jsonb_build_array()
  ),
  now()
)
on conflict (key) do nothing;

alter table public.knowledge_entries enable row level security;
alter table public.world_stats enable row level security;

drop policy if exists "knowledge_read_all" on public.knowledge_entries;
create policy "knowledge_read_all"
on public.knowledge_entries
for select
to anon
using (true);

drop policy if exists "knowledge_insert_all" on public.knowledge_entries;
create policy "knowledge_insert_all"
on public.knowledge_entries
for insert
to anon
with check (true);

drop policy if exists "stats_read_all" on public.world_stats;
create policy "stats_read_all"
on public.world_stats
for select
to anon
using (true);

drop policy if exists "stats_update_all" on public.world_stats;
create policy "stats_update_all"
on public.world_stats
for update
to anon
using (key = 'access_state')
with check (key = 'access_state');

drop policy if exists "stats_insert_all" on public.world_stats;
create policy "stats_insert_all"
on public.world_stats
for insert
to anon
with check (key = 'access_state');
